### ISSUE TITLE
Operating on vectors from different coordinate spaces

### ISSUE THREAD

**Issue by spikeburton** [spikeburton/vector-js#7]
```js
const v1 = new Vector(1, 2, 3);
v1.add([1, 2]);
```

**ERROR**: Error: Operations can only be performed on vectors that inhabit the same coordinate system.
**ERROR**: TypeError: Found non-callable @@iterator

**Comment by allen-woods** [comment]
Restored original error on mismatched dimensional coordinates, fixed "TypeError" thrown by Array.prototype.reduce()
